linters-settings:
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: UK
    ignore-words:
      - serialized # serialized is written with 'z' in the nedap urls
  lll:
    line-length: 100
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - wrapperFunc
      - commentFormatting # https://github.com/go-critic/go-critic/issues/755

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - unused
    - gocyclo
    - golint
    - varcheck
    - structcheck
    - maligned
    - ineffassign
    - interfacer
    - unconvert
    - goconst
    - gosimple
    - staticcheck
    - gosec
    - tparallel
    - nakedret
    - gofmt
    - gocognit
    - godot
    - misspell
    - noctx
    - nolintlint
    - goimports

run:
  deadline: 10m
  skip-dirs:
    - ".*\\testdata"
    - ".*proto"
  skip-files:
    - ".*pb\\.go"
    - ".*pb\\.gw\\.go"
    - assets.go

output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  # format: json

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.36.x # use fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed"
